/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:299731:
  appc.background(230);
} //_CODE_:window1:299731:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:504966:
  if( running == true ) { 
    noLoop();
    running = false;
    pauseButton.setText("Start");
  }
    
  else {
    loop();
    running = true;
    pauseButton.setText("Pause");
  }
  
  println(menu.getSelectedText());
} //_CODE_:pauseButton:504966:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:702112:
  reset();
  menuOn = !menuOn;
  
  menu.setVisible(menuOn);
  
} //_CODE_:resetButton:702112:

public void menuSelect(GDropList source, GEvent event) { //_CODE_:menu:257275:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:menu:257275:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  pauseButton = new GButton(window1, 14, 14, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  resetButton = new GButton(window1, 13, 59, 80, 30);
  resetButton.setText("Reset");
  resetButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  resetButton.addEventHandler(this, "resetButtonClicked");
  menu = new GDropList(window1, 126, 17, 90, 80, 3, 10);
  menu.setItems(loadStrings("list_257275"), 0);
  menu.addEventHandler(this, "menuSelect");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton pauseButton; 
GButton resetButton; 
GDropList menu; 
